# Generated by Django 4.2 on 2024-11-20 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category_persian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Status_persian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project_persian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('caption', models.TextField()),
                ('type', models.CharField(choices=[('تجاری', 'تجاری'), ('ویلا', 'ویلا'), ('آپارتمان', 'آپارتمان'), ('مجتمع مسکونی', 'مجتمع مسکونی'), ('بازسازی', 'بازسازی'), ('صنعتی', 'صنعتی'), ('فضای عمومی', 'فضای عمومی')], max_length=14)),
                ('status', models.CharField(choices=[('تکمیل', 'تکمیل'), ('ایده', 'ایده'), ('در حال اجرا', 'در حال اجرا')], max_length=11)),
                ('location', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=80)),
                ('team', models.CharField(max_length=255)),
                ('architects', models.CharField(default='mobina shafiei', max_length=100)),
                ('constructor', models.CharField(max_length=100)),
                ('scale', models.FloatField(default=100)),
                ('VR_html', models.FileField(blank=True, null=True, upload_to='VRhtmlfiles/')),
                ('category', models.ManyToManyField(to='projects.category_persian')),
                ('status_value', models.ManyToManyField(to='projects.status_persian')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('caption', models.TextField()),
                ('type', models.CharField(choices=[('commercial', 'Commercial'), ('villa', 'Villa'), ('apartment', 'Apartment'), ('residential-co', 'Residetial complex'), ('renovation', 'Renovation'), ('industrial', 'Industrial'), ('public-space', 'Public space')], max_length=14)),
                ('status', models.CharField(choices=[('Completed', 'completed'), ('Concept', 'concept'), ('in progress', 'In progress')], max_length=11)),
                ('design_year', models.DateField(blank=True, null=True)),
                ('location', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=80)),
                ('team', models.CharField(max_length=255)),
                ('architects', models.CharField(default='mobina shafiei', max_length=100)),
                ('constructor', models.CharField(max_length=100)),
                ('scale', models.FloatField(default=100)),
                ('VR_html', models.FileField(blank=True, null=True, upload_to='VRhtmlfiles/')),
                ('category', models.ManyToManyField(to='projects.category')),
                ('status_value', models.ManyToManyField(to='projects.status')),
            ],
        ),
        migrations.CreateModel(
            name='Image_persian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projectimages/')),
                ('related_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project_persian')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projectimages/')),
                ('related_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project')),
            ],
        ),
    ]
