# Generated by Django 4.2 on 2024-11-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_persian',
            name='design_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
