# Generated by Django 4.2 on 2024-11-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_persian_design_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_persian',
            name='status',
            field=models.CharField(choices=[('تکمیل', 'تکمیل'), ('ایده', 'ایده'), ('در حال اجرا', 'در حال اجرا')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project_persian',
            name='type',
            field=models.CharField(choices=[('تجاری', 'تجاری'), ('ویلا', 'ویلا'), ('آپارتمان', 'آپارتمان'), ('مجتمع مسکونی', 'مجتمع مسکونی'), ('بازسازی', 'بازسازی'), ('صنعتی', 'صنعتی'), ('فضای عمومی', 'فضای عمومی')], max_length=20),
        ),
    ]
