# Generated by Django 4.2 on 2024-12-01 10:48

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_persian_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_persian',
            name='design_year',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
