# Generated by Django 4.2 on 2024-11-27 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image_blog',
            old_name='related_project',
            new_name='related_blog',
        ),
    ]
