# Generated by Django 4.2 on 2024-12-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_persian_image_blog_persian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_persian',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
