# Generated by Django 4.2 on 2024-12-01 09:29

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_published_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_persian',
            name='published_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
    ]
