# Generated by Django 4.2 on 2024-12-01 10:40

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_persian_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_persian',
            name='published_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
